<a href="https://colab.research.google.com/github/LazyHooks/Optimus/blob/main/optimus_v2_gcc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import pandas as pd

In [46]:
df = pd.read_csv('gcc_train.csv')
df.head()

,Company Name,Co. Designation,Co. Function,Job Family Code
0,Soc Gen Hi Tech & ITES 2022,Analyst,CENTRAL FUNCTIONS,LECO
1,Soc Gen Hi Tech & ITES 2022,Analyst,KYC&CL Utility (KYU),BFCM
2,Soc Gen Hi Tech & ITES 2022,Cyber Security Senior Analyst,GTS,SYXX
3,Soc Gen Hi Tech & ITES 2022,Cyber Security Analyst,GTS,SYXX
4,Soc Gen Hi Tech & ITES 2022,Senior Analyst,CENTRAL FUNCTIONS,FAFA

In [47]:
df_test = pd.read_csv('gcc_test.csv')
df_test.head()

,Company Name,Co. Designation,Co. Function,Job Family Code
0,Invesco Hi Tech & ITES 2022,Senior Fund Administrator,Fund Administration,BFFU
1,Invesco Hi Tech & ITES 2022,"Trainee, Marketing Ops",Marketing,TOMR
2,Invesco Hi Tech & ITES 2022,"Eng. II, Cloud & Sol",Technology,ASCD
3,Invesco Hi Tech & ITES 2022,"Eng. II, Invest Tech",Technology,ASXX
4,Invesco Hi Tech & ITES 2022,"Eng. II, Invest Tech",Technology,ASXX

In [48]:
df.shape
set(df['Company Name'])

{'ANZ Hi Tech & ITES 2022',
 'Allstate Hi Tech & ITES 2022',
 'BNYM Hitech and ites 2022',
 'BlackRock Services India Pvt Ltd',
 'Citi Corp Hi Tech & ITES 2022',
 'DBOI +DBC',
 'DBS Asia Hub 2',
 'DBSschenker Hi Tech & ITES 2022',
 'FIL',
 'FIS',
 'Fiserv',
 'Greatwest Hi Tech & ITES 2022',
 'HDFC Securities Hi Tech & ITES 2022',
 'IFTAS',
 'Kroll Associates',
 'M&G Global Services Pvt Ltd',
 'Midland Credit Management Hi Tech & ITES 2022',
 'Morning Star Hi Tech & ITES 2022',
 'Nomura Hi Tech & ITES 2022',
 'Northern Trust Hi Tech & ITES 2022',
 'Soc Gen Hi Tech & ITES 2022',
 'Statestreet Hi Tech and Ites 2022',
 'Stripe',
 'Swiss Re',
 'TIAA Hi Tech & ITES 2022',
 'Wells Fargo Hi Tech & ITES 2022'}

In [49]:
df.columns

Index(['Company Name', 'Co. Designation', 'Co. Function', 'Job Family Code'], dtype='object')

In [50]:
train_cols = ['Co. Designation', 'Co. Function']

In [51]:
target_col = 'Job Family Code'

In [52]:
all_cols = ['Co. Designation', 'Co. Function', 'Job Family Code']

In [53]:
import pandas as pd
from scipy.sparse import hstack
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

In [54]:
# Load data
data = pd.read_csv('gcc_train.csv')

In [55]:
df_test.head()

,Company Name,Co. Designation,Co. Function,Job Family Code
0,Invesco Hi Tech & ITES 2022,Senior Fund Administrator,Fund Administration,BFFU
1,Invesco Hi Tech & ITES 2022,"Trainee, Marketing Ops",Marketing,TOMR
2,Invesco Hi Tech & ITES 2022,"Eng. II, Cloud & Sol",Technology,ASCD
3,Invesco Hi Tech & ITES 2022,"Eng. II, Invest Tech",Technology,ASXX
4,Invesco Hi Tech & ITES 2022,"Eng. II, Invest Tech",Technology,ASXX

In [56]:
data = data[all_cols]
data = data.dropna()

In [57]:
df_test = df_test[all_cols]
df_test = df_test.dropna()

In [58]:
data.head()

                 Co. Designation          Co. Function Job Family Code
0                        Analyst     CENTRAL FUNCTIONS            LECO
1                        Analyst  KYC&CL Utility (KYU)            BFCM
2  Cyber Security Senior Analyst                   GTS            SYXX
3         Cyber Security Analyst                   GTS            SYXX
4                 Senior Analyst     CENTRAL FUNCTIONS            FAFA

In [59]:
df_test.head()

             Co. Designation         Co. Function Job Family Code
0  Senior Fund Administrator  Fund Administration            BFFU
1     Trainee, Marketing Ops            Marketing            TOMR
2       Eng. II, Cloud & Sol           Technology            ASCD
3       Eng. II, Invest Tech           Technology            ASXX
4       Eng. II, Invest Tech           Technology            ASXX

In [60]:
# Extract features from each text column using TF-IDF vectorizer
vectorizers = []
X_train_list = []
X_test_list = []
for col in train_cols:
    vectorizer = TfidfVectorizer(max_features=10000)
    X_train_col = vectorizer.fit_transform(data.loc[:, col])
    X_train_list.append(X_train_col)
    X_test_col = vectorizer.transform(data.loc[:, col])
    X_test_list.append(X_test_col)
    vectorizers.append(vectorizer)

In [62]:
# Concatenate sparse matrices into a single feature matrix
X_train = hstack(X_train_list)
X_test = hstack(X_test_list)

# Split data into training and testing sets
y_train = data[target_col]
#y_test = df_test[target_col]

X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [63]:
# Train logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Predict on test set and evaluate performance
y_pred = model.predict(X_test)
print('Accuracy:', accuracy_score(y_test, y_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Accuracy: 0.8439704512178889

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Classification Report:
               precision    recall  f1-score   support

        AADS       0.91      0.84      0.87        86
        AAIB       0.00      0.00      0.00         1
        AAMD       0.83      0.71      0.76       136
        AFAD       0.54      0.68      0.60        40
        AFFE       0.90      0.62      0.73        29
        AFSE       0.96      0.81      0.88        27
        AFXX       1.00      0.33      0.50         6
        ARCD       0.00      0.00      0.00         4
        ARIA       1.00      0.65      0.79        34
        ARMD       0.00      0.00      0.00         1
        ARRP       0.33      0.14      0.20         7
        ARSY       1.00      0.33      0.50         3
        ARXX       0.88      0.88      0.88       150
        ASCD       0.86      0.18      0.29        34
        ASDB       0.97      0.47      0.64        72
        ASEC       1.00      0.33      0.50         9
        ASFS       0.92      0.54      0.68       489
        ASMD       0.00      0.00      0.00        21
        ASPI       1.00      0.15      0.26        53
        ASRP       0.67      0.34      0.45        71
        ASSI       0.30      0.04      0.08        68
        ASUI       0.91      0.76      0.83        55
        ASWD       0.00      0.00      0.00         1
        ASXX       0.82      0.97      0.89      5102
        BCPM       1.00      0.40      0.57        10
        BFAC       0.88      0.96      0.92        51
        BFAM       0.74      0.54      0.63       283
        BFCA       0.97      0.97      0.97       257
        BFCB       0.97      0.90      0.93      1076
        BFCM       0.71      0.83      0.77      1052
        BFFU       0.47      0.94      0.62       370
        BFKY       0.85      0.82      0.83       544
        BFLP       1.00      1.00      1.00        20
        BFPC       0.13      0.08      0.10       195
        BFTF       0.98      0.67      0.80       264
        BFTO       0.86      0.92      0.89      1169
        BFUW       0.77      0.78      0.77        86
        BFWB       0.22      0.41      0.29        82
        BSMT       0.68      0.57      0.62       120
        CCCE       0.88      0.78      0.82         9
        CCCO       1.00      0.11      0.19        28
        CCCV       0.00      0.00      0.00         1
        CCCW       0.00      0.00      0.00        27
        CCMD       0.97      0.97      0.97       186
        CCMI       0.58      0.94      0.72       120
        CCVD       0.81      0.63      0.71       380
        CCVI       1.00      1.00      1.00       498
        CMDO       0.79      0.39      0.53        76
        CMDS       0.00      0.00      0.00         2
        CMXX       1.00      0.82      0.90        49
        CSBC       0.75      0.72      0.73       118
        CSCG       0.00      0.00      0.00         1
        CSCS       0.00      0.00      0.00         7
        CSED       0.00      0.00      0.00         3
        CSEL       0.00      0.00      0.00         2
        CSFC       0.90      0.86      0.88       607
        CSPS       0.00      0.00      0.00         3
        CSSI       0.95      0.92      0.93       143
        DABD       0.70      0.17      0.27        84
        DABI       0.89      0.88      0.88       528
        DADV       1.00      0.18      0.30        17
        DADW       0.74      0.25      0.37        80
        DMDA       0.67      0.43      0.52        61
        DMKM       0.00      0.00      0.00         3
        DMMD       0.00      0.00      0.00        11
        DMSM       0.94      0.32      0.48        99
        EDXX       0.50      1.00      0.67         1
        FAAG       1.00      0.21      0.35        61
        FAAP       0.79      0.46      0.58        24
        FAAU       0.00      0.00      0.00         4
        FADS       0.00      0.00      0.00         8
        FAER       0.76      0.27      0.39       143
        FAFA       0.79      0.62      0.70       229
        FAFI       0.99      0.95      0.97       348
        FALC       0.56      0.88      0.68       158
        FAML       0.92      0.73      0.81       135
        FAPC       0.00      0.00      0.00         1
        FARR       0.83      0.24      0.38        41
        FASR       1.00      0.39      0.56        18
        FATA       0.87      0.62      0.72        21
        FATP       0.00      0.00      0.00         6
        FLAC       0.98      0.95      0.96       195
        FLCS       0.00      0.00      0.00         4
        FLFA       1.00      0.84      0.91        19
        FLLE       0.83      0.88      0.86        17
        FLMI       0.59      0.81      0.68        16
        FLPP       0.93      0.85      0.89        47
        FLPR       1.00      0.86      0.92         7
        FLTR       1.00      0.61      0.76        36
        FLTX       1.00      0.79      0.88        28
        FLXX       0.93      0.94      0.94       353
        GDXX       1.00      1.00      1.00         7
        HCCA       1.00      0.73      0.84        11
        HCMR       1.00      0.69      0.82        29
        HRBP       0.82      0.83      0.83        60
        HRCB       1.00      0.76      0.87        17
        HRDI       0.00      0.00      0.00         1
        HRGM       0.50      0.50      0.50         2
        HROD       0.80      0.57      0.67         7
        HRRE       0.79      0.83      0.81        71
        HRRM       0.00      0.00      0.00         2
        HRSS       1.00      0.20      0.33        10
        HRTR       0.79      0.75      0.77        36
        HRXX       1.00      0.17      0.29         6
        HSCB       0.00      0.00      0.00         1
        HSGL       0.55      0.54      0.54        41
        HSLD       0.00      0.00      0.00         3
        HSPL       0.83      0.75      0.79        20
        HSRS       1.00      0.50      0.67         8
        INAU       0.72      0.87      0.79        53
        INCL       0.67      0.55      0.60        11
        INDB       0.86      0.83      0.85       181
        INDC       1.00      0.25      0.40         4
        INDS       0.76      0.72      0.74       102
        INFS       0.00      0.00      0.00        10
        INNE       0.99      0.88      0.93       153
        INRA       0.92      0.89      0.90       337
        INRE       1.00      0.93      0.97        15
        INRI       1.00      0.97      0.98       416
        INRP       0.14      0.08      0.11        12
        INSA       1.00      0.41      0.58        17
        INSS       0.76      0.92      0.83       197
        INTI       1.00      0.60      0.75         5
        INXX       0.85      0.88      0.87       476
        ITAU       1.00      0.09      0.17        11
        LECO       0.61      0.79      0.69       180
        LEPO       0.50      0.06      0.11        17
        LERE       1.00      1.00      1.00         4
        MBCC       0.95      0.72      0.82        25
        MBCM       1.00      0.67      0.80         6
        MBDM       0.75      0.60      0.67        15
        MBXX       0.69      1.00      0.82        20
        PDFS       0.00      0.00      0.00         9
        PDPM       0.88      0.75      0.81       112
        PDXX       0.98      0.91      0.95      1539
        PRAG       0.87      0.72      0.79       139
        PRPO       0.82      0.88      0.85       351
        PRXX       0.76      0.73      0.75       371
        QAXX       0.00      0.00      0.00        15
        QUTF       0.85      0.80      0.82        91
        QUTS       0.97      0.94      0.95       247
        RABA       0.76      0.77      0.77       291
        RABF       0.75      0.92      0.83       110
        RAPR       0.83      0.83      0.83         6
        RARA       0.88      0.75      0.81       268
        RASR       1.00      0.94      0.97        35
        RAVA       1.00      0.87      0.93        76
        RICR       0.65      0.78      0.71       102
        RIER       0.91      0.48      0.62        61
        RIMR       0.35      0.41      0.38        90
        RIOR       0.92      0.90      0.91       339
        RSSC       1.00      1.00      1.00         6
        RSVM       0.92      0.52      0.67        21
        SAAC       0.90      0.94      0.92       109
        SABD       0.84      0.84      0.84        37
        SACS       1.00      0.75      0.86         8
        SAPS       0.80      0.80      0.80         5
        SASD       0.67      0.93      0.78        15
        SAXX       0.89      0.86      0.88        95
        SCCP       1.00      1.00      1.00        38
        SSSO       0.92      0.80      0.86        30
        SYAM       0.00      0.00      0.00         1
        SYAS       0.83      0.38      0.53        13
        SYGR       1.00      0.57      0.72        37
        SYIM       0.93      0.76      0.83        66
        SYIN       0.68      0.62      0.65        21
        SYIS       0.63      0.65      0.64        34
        SYPT       0.00      0.00      0.00         4
        SYXX       0.85      0.78      0.82       306
        TEAU       0.92      0.93      0.93      1062
        TEMT       0.82      0.70      0.76        44
        TEXX       0.99      0.96      0.98       599
        TOCO       0.91      0.90      0.91       935
        TOFC       0.95      0.93      0.94      1429
        TOFS       0.95      0.94      0.95       143
        TOMR       1.00      0.24      0.39        29
        TOPO       0.77      0.69      0.73        48
        TOSI       0.78      0.98      0.87       814
        TRPR       0.92      0.52      0.67        21
        TRTN       0.00      0.00      0.00         2
        TSXX       0.00      0.00      0.00         2
        TTXX       0.00      0.00      0.00         1
        TWXX       1.00      0.88      0.94        41
        UEXX       1.00      0.71      0.83        17
        asxx       0.00      0.00      0.00         4
        bfam       0.00      0.00      0.00         2
        dmda       0.00      0.00      0.00         2
        edxx       0.00      0.00      0.00         1
        hrdi       0.00      0.00      0.00         1
        indb       0.00      0.00      0.00         1
        inds       0.00      0.00      0.00         2
        pdxx       0.00      0.00      0.00         2
        rabf       0.80      1.00      0.89         4
        rsvm       0.00      0.00      0.00         1
        teau       1.00      0.14      0.25         7

    accuracy                           0.84     30052
   macro avg       0.67      0.54      0.57     30052
weighted avg       0.85      0.84      0.84     30052

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [64]:
X_test_unseen = []

for i, col in enumerate(train_cols):
    vectorizer = vectorizers[i]
    X_test_col = vectorizer.transform(df_test.loc[:, col])
    X_test_unseen.append(X_test_col)
    
X_unseen = hstack(X_test_unseen)

In [65]:
y_test_pred = model.predict (X_unseen)

In [66]:
pd.DataFrame(y_test_pred).to_csv('maps_gcc')

In [68]:
# Predict on test set and evaluate performance
y_test_actual=df_test[target_col]
print('Accuracy:', accuracy_score(y_test_actual, y_test_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))

Accuracy: 0.2639355271994627

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Classification Report:
               precision    recall  f1-score   support

        AADS       0.91      0.84      0.87        86
        AAIB       0.00      0.00      0.00         1
        AAMD       0.83      0.71      0.76       136
        AFAD       0.54      0.68      0.60        40
        AFFE       0.90      0.62      0.73        29
        AFSE       0.96      0.81      0.88        27
        AFXX       1.00      0.33      0.50         6
        ARCD       0.00      0.00      0.00         4
        ARIA       1.00      0.65      0.79        34
        ARMD       0.00      0.00      0.00         1
        ARRP       0.33      0.14      0.20         7
        ARSY       1.00      0.33      0.50         3
        ARXX       0.88      0.88      0.88       150
        ASCD       0.86      0.18      0.29        34
        ASDB       0.97      0.47      0.64        72
        ASEC       1.00      0.33      0.50         9
        ASFS       0.92      0.54      0.68       489
        ASMD       0.00      0.00      0.00        21
        ASPI       1.00      0.15      0.26        53
        ASRP       0.67      0.34      0.45        71
        ASSI       0.30      0.04      0.08        68
        ASUI       0.91      0.76      0.83        55
        ASWD       0.00      0.00      0.00         1
        ASXX       0.82      0.97      0.89      5102
        BCPM       1.00      0.40      0.57        10
        BFAC       0.88      0.96      0.92        51
        BFAM       0.74      0.54      0.63       283
        BFCA       0.97      0.97      0.97       257
        BFCB       0.97      0.90      0.93      1076
        BFCM       0.71      0.83      0.77      1052
        BFFU       0.47      0.94      0.62       370
        BFKY       0.85      0.82      0.83       544
        BFLP       1.00      1.00      1.00        20
        BFPC       0.13      0.08      0.10       195
        BFTF       0.98      0.67      0.80       264
        BFTO       0.86      0.92      0.89      1169
        BFUW       0.77      0.78      0.77        86
        BFWB       0.22      0.41      0.29        82
        BSMT       0.68      0.57      0.62       120
        CCCE       0.88      0.78      0.82         9
        CCCO       1.00      0.11      0.19        28
        CCCV       0.00      0.00      0.00         1
        CCCW       0.00      0.00      0.00        27
        CCMD       0.97      0.97      0.97       186
        CCMI       0.58      0.94      0.72       120
        CCVD       0.81      0.63      0.71       380
        CCVI       1.00      1.00      1.00       498
        CMDO       0.79      0.39      0.53        76
        CMDS       0.00      0.00      0.00         2
        CMXX       1.00      0.82      0.90        49
        CSBC       0.75      0.72      0.73       118
        CSCG       0.00      0.00      0.00         1
        CSCS       0.00      0.00      0.00         7
        CSED       0.00      0.00      0.00         3
        CSEL       0.00      0.00      0.00         2
        CSFC       0.90      0.86      0.88       607
        CSPS       0.00      0.00      0.00         3
        CSSI       0.95      0.92      0.93       143
        DABD       0.70      0.17      0.27        84
        DABI       0.89      0.88      0.88       528
        DADV       1.00      0.18      0.30        17
        DADW       0.74      0.25      0.37        80
        DMDA       0.67      0.43      0.52        61
        DMKM       0.00      0.00      0.00         3
        DMMD       0.00      0.00      0.00        11
        DMSM       0.94      0.32      0.48        99
        EDXX       0.50      1.00      0.67         1
        FAAG       1.00      0.21      0.35        61
        FAAP       0.79      0.46      0.58        24
        FAAU       0.00      0.00      0.00         4
        FADS       0.00      0.00      0.00         8
        FAER       0.76      0.27      0.39       143
        FAFA       0.79      0.62      0.70       229
        FAFI       0.99      0.95      0.97       348
        FALC       0.56      0.88      0.68       158
        FAML       0.92      0.73      0.81       135
        FAPC       0.00      0.00      0.00         1
        FARR       0.83      0.24      0.38        41
        FASR       1.00      0.39      0.56        18
        FATA       0.87      0.62      0.72        21
        FATP       0.00      0.00      0.00         6
        FLAC       0.98      0.95      0.96       195
        FLCS       0.00      0.00      0.00         4
        FLFA       1.00      0.84      0.91        19
        FLLE       0.83      0.88      0.86        17
        FLMI       0.59      0.81      0.68        16
        FLPP       0.93      0.85      0.89        47
        FLPR       1.00      0.86      0.92         7
        FLTR       1.00      0.61      0.76        36
        FLTX       1.00      0.79      0.88        28
        FLXX       0.93      0.94      0.94       353
        GDXX       1.00      1.00      1.00         7
        HCCA       1.00      0.73      0.84        11
        HCMR       1.00      0.69      0.82        29
        HRBP       0.82      0.83      0.83        60
        HRCB       1.00      0.76      0.87        17
        HRDI       0.00      0.00      0.00         1
        HRGM       0.50      0.50      0.50         2
        HROD       0.80      0.57      0.67         7
        HRRE       0.79      0.83      0.81        71
        HRRM       0.00      0.00      0.00         2
        HRSS       1.00      0.20      0.33        10
        HRTR       0.79      0.75      0.77        36
        HRXX       1.00      0.17      0.29         6
        HSCB       0.00      0.00      0.00         1
        HSGL       0.55      0.54      0.54        41
        HSLD       0.00      0.00      0.00         3
        HSPL       0.83      0.75      0.79        20
        HSRS       1.00      0.50      0.67         8
        INAU       0.72      0.87      0.79        53
        INCL       0.67      0.55      0.60        11
        INDB       0.86      0.83      0.85       181
        INDC       1.00      0.25      0.40         4
        INDS       0.76      0.72      0.74       102
        INFS       0.00      0.00      0.00        10
        INNE       0.99      0.88      0.93       153
        INRA       0.92      0.89      0.90       337
        INRE       1.00      0.93      0.97        15
        INRI       1.00      0.97      0.98       416
        INRP       0.14      0.08      0.11        12
        INSA       1.00      0.41      0.58        17
        INSS       0.76      0.92      0.83       197
        INTI       1.00      0.60      0.75         5
        INXX       0.85      0.88      0.87       476
        ITAU       1.00      0.09      0.17        11
        LECO       0.61      0.79      0.69       180
        LEPO       0.50      0.06      0.11        17
        LERE       1.00      1.00      1.00         4
        MBCC       0.95      0.72      0.82        25
        MBCM       1.00      0.67      0.80         6
        MBDM       0.75      0.60      0.67        15
        MBXX       0.69      1.00      0.82        20
        PDFS       0.00      0.00      0.00         9
        PDPM       0.88      0.75      0.81       112
        PDXX       0.98      0.91      0.95      1539
        PRAG       0.87      0.72      0.79       139
        PRPO       0.82      0.88      0.85       351
        PRXX       0.76      0.73      0.75       371
        QAXX       0.00      0.00      0.00        15
        QUTF       0.85      0.80      0.82        91
        QUTS       0.97      0.94      0.95       247
        RABA       0.76      0.77      0.77       291
        RABF       0.75      0.92      0.83       110
        RAPR       0.83      0.83      0.83         6
        RARA       0.88      0.75      0.81       268
        RASR       1.00      0.94      0.97        35
        RAVA       1.00      0.87      0.93        76
        RICR       0.65      0.78      0.71       102
        RIER       0.91      0.48      0.62        61
        RIMR       0.35      0.41      0.38        90
        RIOR       0.92      0.90      0.91       339
        RSSC       1.00      1.00      1.00         6
        RSVM       0.92      0.52      0.67        21
        SAAC       0.90      0.94      0.92       109
        SABD       0.84      0.84      0.84        37
        SACS       1.00      0.75      0.86         8
        SAPS       0.80      0.80      0.80         5
        SASD       0.67      0.93      0.78        15
        SAXX       0.89      0.86      0.88        95
        SCCP       1.00      1.00      1.00        38
        SSSO       0.92      0.80      0.86        30
        SYAM       0.00      0.00      0.00         1
        SYAS       0.83      0.38      0.53        13
        SYGR       1.00      0.57      0.72        37
        SYIM       0.93      0.76      0.83        66
        SYIN       0.68      0.62      0.65        21
        SYIS       0.63      0.65      0.64        34
        SYPT       0.00      0.00      0.00         4
        SYXX       0.85      0.78      0.82       306
        TEAU       0.92      0.93      0.93      1062
        TEMT       0.82      0.70      0.76        44
        TEXX       0.99      0.96      0.98       599
        TOCO       0.91      0.90      0.91       935
        TOFC       0.95      0.93      0.94      1429
        TOFS       0.95      0.94      0.95       143
        TOMR       1.00      0.24      0.39        29
        TOPO       0.77      0.69      0.73        48
        TOSI       0.78      0.98      0.87       814
        TRPR       0.92      0.52      0.67        21
        TRTN       0.00      0.00      0.00         2
        TSXX       0.00      0.00      0.00         2
        TTXX       0.00      0.00      0.00         1
        TWXX       1.00      0.88      0.94        41
        UEXX       1.00      0.71      0.83        17
        asxx       0.00      0.00      0.00         4
        bfam       0.00      0.00      0.00         2
        dmda       0.00      0.00      0.00         2
        edxx       0.00      0.00      0.00         1
        hrdi       0.00      0.00      0.00         1
        indb       0.00      0.00      0.00         1
        inds       0.00      0.00      0.00         2
        pdxx       0.00      0.00      0.00         2
        rabf       0.80      1.00      0.89         4
        rsvm       0.00      0.00      0.00         1
        teau       1.00      0.14      0.25         7

    accuracy                           0.84     30052
   macro avg       0.67      0.54      0.57     30052
weighted avg       0.85      0.84      0.84     30052

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
df_test