<a href="https://colab.research.google.com/github/LazyHooks/Optimus/blob/main/optimus_v2_gcc_gccprod.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import pandas as pd

In [41]:
df = pd.read_csv('gcc_trainsim.csv')
df.head()

,Company Name,Co. Designation,Co. Function,Job Family Code
0,Soc Gen Hi Tech & ITES 2022,Analyst,CENTRAL FUNCTIONS,LECO
1,Soc Gen Hi Tech & ITES 2022,Analyst,KYC&CL Utility (KYU),BFCM
2,Soc Gen Hi Tech & ITES 2022,Cyber Security Senior Analyst,GTS,SYXX
3,Soc Gen Hi Tech & ITES 2022,Cyber Security Analyst,GTS,SYXX
4,Soc Gen Hi Tech & ITES 2022,Senior Analyst,CENTRAL FUNCTIONS,FAFA

In [42]:
df_test = pd.read_csv('gcc_test.csv')
df_test.head()

,Company Name,Co. Designation,Co. Function,Job Family Code
0,Invesco Hi Tech & ITES 2022,Senior Fund Administrator,Fund Administration,BFFU
1,Invesco Hi Tech & ITES 2022,"Trainee, Marketing Ops",Marketing,TOMR
2,Invesco Hi Tech & ITES 2022,"Eng. II, Cloud & Sol",Technology,ASCD
3,Invesco Hi Tech & ITES 2022,"Eng. II, Invest Tech",Technology,ASXX
4,Invesco Hi Tech & ITES 2022,"Eng. II, Invest Tech",Technology,ASXX

In [43]:
df.shape
set(df['Company Name'])

{'ANZ Hi Tech & ITES 2022',
 'Allstate Hi Tech & ITES 2022',
 'BNYM Hitech and ites 2022',
 'BlackRock Services India Pvt Ltd',
 'Citi Corp Hi Tech & ITES 2022',
 'DBOI +DBC',
 'DBS Asia Hub 2',
 'DBSschenker Hi Tech & ITES 2022',
 'FIL',
 'FIS',
 'Fiserv',
 'Greatwest Hi Tech & ITES 2022',
 'HDFC Securities Hi Tech & ITES 2022',
 'IFTAS',
 'Inv Dum',
 'Kroll Associates',
 'M&G Global Services Pvt Ltd',
 'Midland Credit Management Hi Tech & ITES 2022',
 'Morning Star Hi Tech & ITES 2022',
 'Nomura Hi Tech & ITES 2022',
 'Northern Trust Hi Tech & ITES 2022',
 'Soc Gen Hi Tech & ITES 2022',
 'Statestreet Hi Tech and Ites 2022',
 'Stripe',
 'Swiss Re',
 'TIAA Hi Tech & ITES 2022',
 'Wells Fargo Hi Tech & ITES 2022'}

In [44]:
df.columns

Index(['Company Name', 'Co. Designation', 'Co. Function', 'Job Family Code'], dtype='object')

In [45]:
train_cols = ['Co. Designation', 'Co. Function']

In [46]:
target_col = 'Job Family Code'

In [47]:
all_cols = ['Co. Designation', 'Co. Function', 'Job Family Code']

In [48]:
import pandas as pd
from scipy.sparse import hstack
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

In [49]:
# Load data
data = pd.read_csv('gcc_trainsim.csv')

In [50]:
df_test.head()

,Company Name,Co. Designation,Co. Function,Job Family Code
0,Invesco Hi Tech & ITES 2022,Senior Fund Administrator,Fund Administration,BFFU
1,Invesco Hi Tech & ITES 2022,"Trainee, Marketing Ops",Marketing,TOMR
2,Invesco Hi Tech & ITES 2022,"Eng. II, Cloud & Sol",Technology,ASCD
3,Invesco Hi Tech & ITES 2022,"Eng. II, Invest Tech",Technology,ASXX
4,Invesco Hi Tech & ITES 2022,"Eng. II, Invest Tech",Technology,ASXX

In [51]:
data = data[all_cols]
data = data.dropna()

In [52]:
df_test = df_test[all_cols]
df_test = df_test.dropna()

In [53]:
data.head()

                 Co. Designation          Co. Function Job Family Code
0                        Analyst     CENTRAL FUNCTIONS            LECO
1                        Analyst  KYC&CL Utility (KYU)            BFCM
2  Cyber Security Senior Analyst                   GTS            SYXX
3         Cyber Security Analyst                   GTS            SYXX
4                 Senior Analyst     CENTRAL FUNCTIONS            FAFA

In [54]:
df_test.head()

             Co. Designation         Co. Function Job Family Code
0  Senior Fund Administrator  Fund Administration            BFFU
1     Trainee, Marketing Ops            Marketing            TOMR
2       Eng. II, Cloud & Sol           Technology            ASCD
3       Eng. II, Invest Tech           Technology            ASXX
4       Eng. II, Invest Tech           Technology            ASXX

In [55]:
# Extract features from each text column using TF-IDF vectorizer
vectorizers = []
X_train_list = []
X_test_list = []
for col in train_cols:
    vectorizer = TfidfVectorizer(max_features=10000)
    X_train_col = vectorizer.fit_transform(data.loc[:, col])
    X_train_list.append(X_train_col)
    X_test_col = vectorizer.transform(data.loc[:, col])
    X_test_list.append(X_test_col)
    vectorizers.append(vectorizer)

In [56]:
# Concatenate sparse matrices into a single feature matrix
X_train = hstack(X_train_list)
X_test = hstack(X_test_list)

# Split data into training and testing sets
y_train = data[target_col]
#y_test = df_test[target_col]

X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [57]:
# Train logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Predict on test set and evaluate performance
y_pred = model.predict(X_test)
print('Accuracy:', accuracy_score(y_test, y_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Accuracy: 0.8425370675453048

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Classification Report:
               precision    recall  f1-score   support

        AADS       0.92      0.74      0.82        90
        AAIB       0.00      0.00      0.00         1
        AAMD       0.85      0.79      0.82       131
        AFAD       0.43      0.73      0.54        33
        AFFE       0.95      0.59      0.73        32
        AFSE       0.94      0.80      0.86        20
        AFXX       1.00      0.40      0.57         5
        ARCD       0.00      0.00      0.00         3
        ARIA       0.97      0.73      0.83        48
        ARMD       0.00      0.00      0.00         2
        ARRP       0.00      0.00      0.00         9
        ARSY       1.00      0.50      0.67         2
        ARXX       0.91      0.89      0.90       167
        ASCD       0.88      0.17      0.28        42
        ASDB       0.97      0.47      0.64        72
        ASEC       1.00      0.20      0.33        10
        ASFS       0.92      0.56      0.70       516
        ASMD       0.00      0.00      0.00        19
        ASPI       1.00      0.24      0.38        51
        ASRP       0.66      0.30      0.41        70
        ASSI       0.80      0.05      0.10        74
        ASUI       0.88      0.73      0.80        52
        ASWD       0.00      0.00      0.00         1
        ASXX       0.81      0.98      0.89      5274
        BCPM       1.00      0.22      0.36         9
        BFAC       0.89      0.93      0.91        42
        BFAM       0.73      0.56      0.63       273
        BFCA       0.98      0.98      0.98       275
        BFCB       0.96      0.90      0.93      1069
        BFCM       0.68      0.83      0.75      1019
        BFFU       0.46      0.93      0.62       365
        BFKY       0.86      0.75      0.80       533
        BFLP       1.00      1.00      1.00        21
        BFPC       0.14      0.07      0.09       194
        BFTF       0.97      0.67      0.80       263
        BFTO       0.85      0.93      0.89      1142
        BFUW       0.75      0.72      0.74        69
        BFWB       0.32      0.50      0.39       111
        BSMT       0.77      0.57      0.65       127
        CCCE       0.88      0.88      0.88         8
        CCCO       1.00      0.10      0.19        29
        CCCV       0.00      0.00      0.00         2
        CCCW       0.00      0.00      0.00        27
        CCMD       0.97      0.97      0.97       184
        CCMI       0.58      0.94      0.72       115
        CCVD       0.81      0.64      0.71       376
        CCVI       1.00      1.00      1.00       507
        CMDO       0.74      0.37      0.49        63
        CMDS       0.00      0.00      0.00         2
        CMXX       1.00      0.86      0.92        57
        CSBC       0.76      0.76      0.76       103
        CSCS       0.00      0.00      0.00         6
        CSED       0.00      0.00      0.00         2
        CSEL       0.25      1.00      0.40         2
        CSFC       0.90      0.86      0.88       610
        CSPS       0.00      0.00      0.00         3
        CSSI       0.96      0.92      0.94       137
        DABD       0.53      0.10      0.17        88
        DABI       0.92      0.86      0.89       540
        DADV       1.00      0.12      0.21        17
        DADW       0.66      0.29      0.41        85
        DMDA       0.65      0.42      0.51        57
        DMKM       0.00      0.00      0.00         2
        DMMD       0.00      0.00      0.00         9
        DMSM       0.82      0.32      0.46       115
        EDXX       0.80      0.80      0.80         5
        FAAG       0.94      0.36      0.52        81
        FAAP       0.81      0.69      0.75        32
        FAAU       0.00      0.00      0.00         4
        FADS       0.00      0.00      0.00         4
        FAER       0.91      0.20      0.33       142
        FAFA       0.81      0.62      0.70       243
        FAFI       0.99      0.96      0.97       353
        FALC       0.53      0.89      0.67       142
        FAML       0.93      0.74      0.82       156
        FARR       0.86      0.28      0.42        43
        FASR       1.00      0.38      0.55        16
        FATA       1.00      0.78      0.88        18
        FATP       0.00      0.00      0.00         5
        FLAC       0.98      0.96      0.97       210
        FLCS       0.00      0.00      0.00         4
        FLFA       1.00      0.87      0.93        23
        FLLE       0.67      0.82      0.73        22
        FLMI       0.62      0.81      0.70        16
        FLPP       0.94      0.85      0.89        34
        FLPR       0.86      0.86      0.86         7
        FLTR       0.92      0.55      0.69        44
        FLTX       0.96      0.79      0.87        34
        FLXX       0.92      0.95      0.93       331
        GDXX       0.91      0.77      0.83        13
        HCCA       1.00      0.77      0.87        13
        HCMR       1.00      0.72      0.84        29
        HRBP       0.76      0.85      0.81        61
        HRCB       1.00      0.72      0.84        18
        HRDI       0.00      0.00      0.00         1
        HRGM       0.00      0.00      0.00         4
        HROD       1.00      0.73      0.84        11
        HRRE       0.78      0.92      0.85        75
        HRRM       0.00      0.00      0.00         2
        HRSS       0.00      0.00      0.00         9
        HRTR       0.81      0.67      0.73        33
        HRXX       1.00      0.10      0.18        10
        HSGL       0.61      0.52      0.56        48
        HSLD       0.00      0.00      0.00         2
        HSPL       0.94      0.71      0.81        21
        HSRS       1.00      0.67      0.80         3
        HSSC       0.00      0.00      0.00         1
        INAU       0.72      0.91      0.81        64
        INCL       0.57      0.67      0.62        12
        INDB       0.86      0.84      0.85       179
        INDC       0.00      0.00      0.00         2
        INDS       0.72      0.68      0.70       111
        INFS       0.00      0.00      0.00         8
        INNE       0.99      0.84      0.91       157
        INRA       0.94      0.90      0.92       374
        INRE       1.00      0.90      0.95        10
        INRI       1.00      0.98      0.99       415
        INRP       0.44      0.36      0.40        11
        INSA       1.00      0.35      0.52        17
        INSS       0.77      0.93      0.84       230
        INTI       1.00      0.60      0.75         5
        INXX       0.84      0.85      0.84       504
        ITAU       0.00      0.00      0.00        17
        LECO       0.63      0.84      0.72       198
        LEPO       1.00      0.08      0.15        25
        LERE       1.00      1.00      1.00         3
        MBCC       0.82      0.82      0.82        17
        MBCM       0.43      0.43      0.43         7
        MBDM       0.92      0.65      0.76        17
        MBSE       0.00      0.00      0.00         1
        MBXX       0.75      0.75      0.75        28
        PDFS       0.00      0.00      0.00        12
        PDPM       0.88      0.78      0.82        99
        PDXX       0.98      0.91      0.94      1513
        PRAG       0.85      0.76      0.80       137
        PRPO       0.82      0.89      0.86       295
        PRXX       0.75      0.71      0.73       368
        QAXX       0.00      0.00      0.00        20
        QUTF       0.85      0.76      0.80        93
        QUTS       0.97      0.95      0.96       238
        RABA       0.79      0.80      0.80       311
        RABF       0.74      0.92      0.82       100
        RAPR       0.83      1.00      0.91         5
        RARA       0.90      0.72      0.80       232
        RASR       1.00      0.90      0.95        49
        RAVA       0.97      0.85      0.91        88
        RICR       0.64      0.79      0.71        99
        RIER       0.93      0.71      0.80        55
        RIMR       0.34      0.38      0.36        90
        RIOR       0.92      0.92      0.92       338
        RSSC       1.00      1.00      1.00         5
        RSVM       0.83      0.45      0.59        22
        SAAC       0.91      0.91      0.91       106
        SABD       0.86      0.86      0.86        37
        SACS       1.00      0.33      0.50        12
        SAPS       1.00      0.40      0.57        10
        SASD       0.62      0.94      0.75        16
        SAXX       0.89      0.91      0.90       102
        SCCP       1.00      0.98      0.99        45
        SSSO       0.95      0.80      0.87        25
        SYAS       0.80      0.57      0.67        14
        SYGR       1.00      0.44      0.61        41
        SYIM       0.97      0.68      0.80        84
        SYIN       0.61      0.74      0.67        19
        SYIS       0.68      0.60      0.63        42
        SYPT       0.00      0.00      0.00         7
        SYXX       0.85      0.76      0.80       298
        TEAU       0.93      0.93      0.93      1062
        TEMT       0.91      0.71      0.80        45
        TEXX       0.98      0.97      0.98       602
        TOCO       0.91      0.90      0.91       931
        TOFC       0.95      0.92      0.94      1443
        TOFS       0.93      0.93      0.93       142
        TOMR       0.96      0.50      0.66        50
        TOPO       0.55      0.62      0.58        26
        TOSI       0.77      0.97      0.86       789
        TRPR       0.94      0.57      0.71        28
        TRTN       0.00      0.00      0.00         2
        TTXX       0.00      0.00      0.00         1
        TWXX       1.00      0.86      0.93        37
        UEXX       1.00      0.76      0.86        21
        asxx       0.00      0.00      0.00         4
        bfam       0.00      0.00      0.00         1
        edxx       0.83      0.83      0.83         6
        indb       0.00      0.00      0.00         1
        inds       0.00      0.00      0.00         2
        leco       0.00      0.00      0.00         1
        pdxx       0.00      0.00      0.00         2
        rabf       0.75      1.00      0.86         3
        rsvm       0.00      0.00      0.00         1
        teau       0.25      0.17      0.20         6

    accuracy                           0.84     30350
   macro avg       0.67      0.55      0.58     30350
weighted avg       0.85      0.84      0.83     30350

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [58]:
X_test_unseen = []

for i, col in enumerate(train_cols):
    vectorizer = vectorizers[i]
    X_test_col = vectorizer.transform(df_test.loc[:, col])
    X_test_unseen.append(X_test_col)
    
X_unseen = hstack(X_test_unseen)

In [59]:
y_test_pred = model.predict (X_unseen)

In [60]:
pd.DataFrame(y_test_pred).to_csv('maps_gccsim')

In [61]:
# Predict on test set and evaluate performance
y_test_actual=df_test[target_col]
print('Accuracy:', accuracy_score(y_test_actual, y_test_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))

Accuracy: 0.7716588314304903

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Classification Report:
               precision    recall  f1-score   support

        AADS       0.92      0.74      0.82        90
        AAIB       0.00      0.00      0.00         1
        AAMD       0.85      0.79      0.82       131
        AFAD       0.43      0.73      0.54        33
        AFFE       0.95      0.59      0.73        32
        AFSE       0.94      0.80      0.86        20
        AFXX       1.00      0.40      0.57         5
        ARCD       0.00      0.00      0.00         3
        ARIA       0.97      0.73      0.83        48
        ARMD       0.00      0.00      0.00         2
        ARRP       0.00      0.00      0.00         9
        ARSY       1.00      0.50      0.67         2
        ARXX       0.91      0.89      0.90       167
        ASCD       0.88      0.17      0.28        42
        ASDB       0.97      0.47      0.64        72
        ASEC       1.00      0.20      0.33        10
        ASFS       0.92      0.56      0.70       516
        ASMD       0.00      0.00      0.00        19
        ASPI       1.00      0.24      0.38        51
        ASRP       0.66      0.30      0.41        70
        ASSI       0.80      0.05      0.10        74
        ASUI       0.88      0.73      0.80        52
        ASWD       0.00      0.00      0.00         1
        ASXX       0.81      0.98      0.89      5274
        BCPM       1.00      0.22      0.36         9
        BFAC       0.89      0.93      0.91        42
        BFAM       0.73      0.56      0.63       273
        BFCA       0.98      0.98      0.98       275
        BFCB       0.96      0.90      0.93      1069
        BFCM       0.68      0.83      0.75      1019
        BFFU       0.46      0.93      0.62       365
        BFKY       0.86      0.75      0.80       533
        BFLP       1.00      1.00      1.00        21
        BFPC       0.14      0.07      0.09       194
        BFTF       0.97      0.67      0.80       263
        BFTO       0.85      0.93      0.89      1142
        BFUW       0.75      0.72      0.74        69
        BFWB       0.32      0.50      0.39       111
        BSMT       0.77      0.57      0.65       127
        CCCE       0.88      0.88      0.88         8
        CCCO       1.00      0.10      0.19        29
        CCCV       0.00      0.00      0.00         2
        CCCW       0.00      0.00      0.00        27
        CCMD       0.97      0.97      0.97       184
        CCMI       0.58      0.94      0.72       115
        CCVD       0.81      0.64      0.71       376
        CCVI       1.00      1.00      1.00       507
        CMDO       0.74      0.37      0.49        63
        CMDS       0.00      0.00      0.00         2
        CMXX       1.00      0.86      0.92        57
        CSBC       0.76      0.76      0.76       103
        CSCS       0.00      0.00      0.00         6
        CSED       0.00      0.00      0.00         2
        CSEL       0.25      1.00      0.40         2
        CSFC       0.90      0.86      0.88       610
        CSPS       0.00      0.00      0.00         3
        CSSI       0.96      0.92      0.94       137
        DABD       0.53      0.10      0.17        88
        DABI       0.92      0.86      0.89       540
        DADV       1.00      0.12      0.21        17
        DADW       0.66      0.29      0.41        85
        DMDA       0.65      0.42      0.51        57
        DMKM       0.00      0.00      0.00         2
        DMMD       0.00      0.00      0.00         9
        DMSM       0.82      0.32      0.46       115
        EDXX       0.80      0.80      0.80         5
        FAAG       0.94      0.36      0.52        81
        FAAP       0.81      0.69      0.75        32
        FAAU       0.00      0.00      0.00         4
        FADS       0.00      0.00      0.00         4
        FAER       0.91      0.20      0.33       142
        FAFA       0.81      0.62      0.70       243
        FAFI       0.99      0.96      0.97       353
        FALC       0.53      0.89      0.67       142
        FAML       0.93      0.74      0.82       156
        FARR       0.86      0.28      0.42        43
        FASR       1.00      0.38      0.55        16
        FATA       1.00      0.78      0.88        18
        FATP       0.00      0.00      0.00         5
        FLAC       0.98      0.96      0.97       210
        FLCS       0.00      0.00      0.00         4
        FLFA       1.00      0.87      0.93        23
        FLLE       0.67      0.82      0.73        22
        FLMI       0.62      0.81      0.70        16
        FLPP       0.94      0.85      0.89        34
        FLPR       0.86      0.86      0.86         7
        FLTR       0.92      0.55      0.69        44
        FLTX       0.96      0.79      0.87        34
        FLXX       0.92      0.95      0.93       331
        GDXX       0.91      0.77      0.83        13
        HCCA       1.00      0.77      0.87        13
        HCMR       1.00      0.72      0.84        29
        HRBP       0.76      0.85      0.81        61
        HRCB       1.00      0.72      0.84        18
        HRDI       0.00      0.00      0.00         1
        HRGM       0.00      0.00      0.00         4
        HROD       1.00      0.73      0.84        11
        HRRE       0.78      0.92      0.85        75
        HRRM       0.00      0.00      0.00         2
        HRSS       0.00      0.00      0.00         9
        HRTR       0.81      0.67      0.73        33
        HRXX       1.00      0.10      0.18        10
        HSGL       0.61      0.52      0.56        48
        HSLD       0.00      0.00      0.00         2
        HSPL       0.94      0.71      0.81        21
        HSRS       1.00      0.67      0.80         3
        HSSC       0.00      0.00      0.00         1
        INAU       0.72      0.91      0.81        64
        INCL       0.57      0.67      0.62        12
        INDB       0.86      0.84      0.85       179
        INDC       0.00      0.00      0.00         2
        INDS       0.72      0.68      0.70       111
        INFS       0.00      0.00      0.00         8
        INNE       0.99      0.84      0.91       157
        INRA       0.94      0.90      0.92       374
        INRE       1.00      0.90      0.95        10
        INRI       1.00      0.98      0.99       415
        INRP       0.44      0.36      0.40        11
        INSA       1.00      0.35      0.52        17
        INSS       0.77      0.93      0.84       230
        INTI       1.00      0.60      0.75         5
        INXX       0.84      0.85      0.84       504
        ITAU       0.00      0.00      0.00        17
        LECO       0.63      0.84      0.72       198
        LEPO       1.00      0.08      0.15        25
        LERE       1.00      1.00      1.00         3
        MBCC       0.82      0.82      0.82        17
        MBCM       0.43      0.43      0.43         7
        MBDM       0.92      0.65      0.76        17
        MBSE       0.00      0.00      0.00         1
        MBXX       0.75      0.75      0.75        28
        PDFS       0.00      0.00      0.00        12
        PDPM       0.88      0.78      0.82        99
        PDXX       0.98      0.91      0.94      1513
        PRAG       0.85      0.76      0.80       137
        PRPO       0.82      0.89      0.86       295
        PRXX       0.75      0.71      0.73       368
        QAXX       0.00      0.00      0.00        20
        QUTF       0.85      0.76      0.80        93
        QUTS       0.97      0.95      0.96       238
        RABA       0.79      0.80      0.80       311
        RABF       0.74      0.92      0.82       100
        RAPR       0.83      1.00      0.91         5
        RARA       0.90      0.72      0.80       232
        RASR       1.00      0.90      0.95        49
        RAVA       0.97      0.85      0.91        88
        RICR       0.64      0.79      0.71        99
        RIER       0.93      0.71      0.80        55
        RIMR       0.34      0.38      0.36        90
        RIOR       0.92      0.92      0.92       338
        RSSC       1.00      1.00      1.00         5
        RSVM       0.83      0.45      0.59        22
        SAAC       0.91      0.91      0.91       106
        SABD       0.86      0.86      0.86        37
        SACS       1.00      0.33      0.50        12
        SAPS       1.00      0.40      0.57        10
        SASD       0.62      0.94      0.75        16
        SAXX       0.89      0.91      0.90       102
        SCCP       1.00      0.98      0.99        45
        SSSO       0.95      0.80      0.87        25
        SYAS       0.80      0.57      0.67        14
        SYGR       1.00      0.44      0.61        41
        SYIM       0.97      0.68      0.80        84
        SYIN       0.61      0.74      0.67        19
        SYIS       0.68      0.60      0.63        42
        SYPT       0.00      0.00      0.00         7
        SYXX       0.85      0.76      0.80       298
        TEAU       0.93      0.93      0.93      1062
        TEMT       0.91      0.71      0.80        45
        TEXX       0.98      0.97      0.98       602
        TOCO       0.91      0.90      0.91       931
        TOFC       0.95      0.92      0.94      1443
        TOFS       0.93      0.93      0.93       142
        TOMR       0.96      0.50      0.66        50
        TOPO       0.55      0.62      0.58        26
        TOSI       0.77      0.97      0.86       789
        TRPR       0.94      0.57      0.71        28
        TRTN       0.00      0.00      0.00         2
        TTXX       0.00      0.00      0.00         1
        TWXX       1.00      0.86      0.93        37
        UEXX       1.00      0.76      0.86        21
        asxx       0.00      0.00      0.00         4
        bfam       0.00      0.00      0.00         1
        edxx       0.83      0.83      0.83         6
        indb       0.00      0.00      0.00         1
        inds       0.00      0.00      0.00         2
        leco       0.00      0.00      0.00         1
        pdxx       0.00      0.00      0.00         2
        rabf       0.75      1.00      0.86         3
        rsvm       0.00      0.00      0.00         1
        teau       0.25      0.17      0.20         6

    accuracy                           0.84     30350
   macro avg       0.67      0.55      0.58     30350
weighted avg       0.85      0.84      0.83     30350

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [62]:
df_test

                   Co. Designation         Co. Function Job Family Code
0        Senior Fund Administrator  Fund Administration            BFFU
1           Trainee, Marketing Ops            Marketing            TOMR
2             Eng. II, Cloud & Sol           Technology            ASCD
3             Eng. II, Invest Tech           Technology            ASXX
4             Eng. II, Invest Tech           Technology            ASXX
...                            ...                  ...             ...
1484  Sr Analyst I-Application Sec           Technology            SYAS
1485         Adv. Eng. I, Ent Arch           Technology            ARXX
1486         Eng. II, Eng Services           Technology            ASXX
1487          Eng. II, Invest Tech           Technology            ASXX
1488          Eng. II, Invest Tech           Technology            ASXX

[1489 rows x 3 columns]